"""Updated project description to be nullable

Revision ID: 00db077d507b
Revises: 70023127a359
Create Date: 2024-07-13 16:20:20.258997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00db077d507b'
down_revision = '70023127a359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
