"""Added completed field

Revision ID: 132bc1955e2f
Revises: 6b2ecaf8d31b
Create Date: 2024-10-19 18:25:08.777481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132bc1955e2f'
down_revision = '6b2ecaf8d31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
