"""Added tokeblasklist model

Revision ID: 694d4f7aaaf6
Revises: de0f6fd381ad
Create Date: 2024-07-31 01:19:38.418300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694d4f7aaaf6'
down_revision = 'de0f6fd381ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
