"""Updated password_hash column to a Text field from String

Revision ID: 70023127a359
Revises: dd80fddd92cd
Create Date: 2024-07-13 11:21:55.335589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70023127a359'
down_revision = 'dd80fddd92cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
