"""Removed task_id column

Revision ID: 8278af3b019d
Revises: ef13db2a8da1
Create Date: 2024-10-28 20:09:29.706906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8278af3b019d'
down_revision = 'ef13db2a8da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('activities_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('activities_task_id_fkey', 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
