"""Added additional fields to project relation

Revision ID: b56182568bd3
Revises: 132bc1955e2f
Create Date: 2024-10-21 19:36:13.484315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56182568bd3'
down_revision = '132bc1955e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('deadline')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
